### ISSUE TITLE
Super heavy repo (> 150Mb) !

### ISSUE THREAD

**Issue by edouard-lopez** [drumrollhq/E.A.K.#121]
I'm updating my fork to –finally– translate into french, but what a surprise to see haw long it take to fetch the code. 
```
git fetch upstream
remote: Counting objects: 8655, done.
remote: Compressing objects: 100% (205/205), done.
Receiving objects:  12% (1124/8655), 68.66 MiB | 168.00 KiB/s
remote: Total 8655 (delta 435), reused 345 (delta 345), pack-reused 8098
Receiving objects: 100% (8655/8655), 168.15 MiB | 423.00 KiB/s, done.
Resolving deltas: 100% (5456/5456), completed with 68 local objects.
```
It took `461s` or  **`~7min` to fetch all the code**.

### Analysis

![erase-all-the-kittens](https://cloud.githubusercontent.com/assets/1212392/10021259/8cf1c5ae-6147-11e5-95fb-5927b257d15f.png)

The red part is the `kittens/` directory, green part is `.git/` directory probably storing your image as massive blobs.

I know you have been busy since last time I checked but a quick analyse show most of this is due to your `.gif` files. As your project is web-games, why not use online gif ? Either with:

* reducing the number of gifs: you can reuse some of them or fetch them as needed ;
* hardcoded URL: will require to check link aren't broken ;
* make API calls: for instance using [giphy](https://giphy.com/search/kittens/3) or similar service when level is starting.

**Comment by SomeHats** [comment]
The gifs in E.A.K. need to have certain dimensions and length of animation, so we can't just grab then via an api. Also, E.A.K. needs to work offline - so fetching them from an external source at runtime isn't an option.

Doing a shallow clone helps a little - `git clone --depth 10` downloads 101.15 MiB vs 173.28 MiB for a normal `git clone`. 

I'm closing this as wontfix for now - doing a full clone / pulling a year+ worth of changes is something that happens infrequently enough for this not to be a huge issue. I'll update the readme to suggest using a shallow clone though.

Also: awesome that you're able to help us translate the game! BUT, we're going to be releasing a new version pretty soon (see the `dev` branch), which has a whole load of regressions in terms of localization support. I'll be working on updating this once we've released in a few weeks time, but beware that you might find things pretty frustrating until then.
