### ISSUE TITLE
Reconsider license (use AGPL instead of GPL)

### ISSUE THREAD

**Issue by rugk** [drumrollhq/E.A.K.#150]
Instead of using the GPL, possible the [AGPL](https://en.wikipedia.org/wiki/Affero_General_Public_License) would be the better choice as when using the GPL for server software there is a "license hole" in the GPL, which does not force to publish the source code when the software is executed on a server.

**Comment by SomeHats** [comment]
There's no server-side code in this repo - the entire game runs in-browser, so the issues that the AGPL addresses don't apply here.
